### ISSUE TITLE
site-sidebar_files disappear on mobile

### ISSUE THREAD

**Issue by zubayrrr** [hikerpig/gatsby-project-kb#10]
site-sidebar_files disappear on mobile after navigating from the index file to some other file.

![image](https://user-images.githubusercontent.com/31969517/119280657-f98ae600-bc4f-11eb-9bac-24dea5c5227d.png)

thank you for this great theme.

**Comment by lenowac** [comment]
I just set it up today, but it looks like its still present: 
![image](https://user-images.githubusercontent.com/73599243/120504316-527f1a80-c3c4-11eb-8553-06d58dfab6ff.png)

I used the foam repo template, could that be an outdated version?

Best regards, leo

**Comment by hikerpig** [comment]
@lenowac Thank you for mentioning this. Yes it's because of outdated version. I just found that https://foam-template-gatsby-kb.vercel.app/ has this issue, too.  BTW, I have another bugfix today to release, when the new version is out then I will update the foam-template page and send you the correct version.

**Comment by hikerpig** [comment]
@lenowac the foam template's dependency has upgraded to gatsby-theme-kb@0.7.5 and the demo page has been redeployed.
You can try to run `yarn add gatsby-theme-kb` in the `_layouts` directory.

**Comment by lenowac** [comment]
awesome ^^

thanks for your work, its really nice :)
