### ISSUE TITLE
Add comment plugin to this theme

### ISSUE THREAD

**Issue by flashshare** [hikerpig/gatsby-project-kb#24]
It is possible to add utterances or GraphComment to the blog template in this theme?

Sorry. This is not an issue. Just a question
Thanks

**Comment by hikerpig** [comment]
Aha, I didn't know about GraphComment before, thanks.
Technically it's all possible through Gatsby's [Shadowing](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/) feature. 
I think it's better for you to shadow some of the component than directly adding it to the theme.

If you don't have the experience or time, maybe I can try to write a simple doc on adding utterances in a separate project.

**Comment by flashshare** [comment]
@hikerpig thanks. This is my first time use gatsby. It will be nice if you can write a simple tutorial about this.
But I will try  to use Shadowing first

**Comment by hikerpig** [comment]
@flashshare Thank you for mentioning katex in the other repo, I guess I need to upgrade the dependencies and publish a new version.
And I also find that gatsby-theme-kb is not very easy to shadow, I find the shadowing process a little confusing after not paying close attention to Gatsby's API after a while now ( since I've started a new time-consuming side-project 😂 for some months now ). 
I will write the tutorial this week, maybe some little adjustments are needed for gatsby-theme-kb's exports.

**Comment by hikerpig** [comment]
@flashshare A tutorial of adding utterances ✌. https://gatsby-project-kb.vercel.app/examples/comment-system

**Comment by flashshare** [comment]
@hikerpig Great! Dark and light mode also works well with the comment system!!
